### ISSUE TITLE
Mixed model assumption checks

### ISSUE THREAD

**Issue by barnabuskev** [gamlj/gamlj#102]
Thank you for your great module. Are you planning on doing assumption checks for mixed models?

**Comment by mcfanda** [comment]
Yes, I'm working on it

**Comment by nahorp** [comment]
Firstly, indeed, thank you for a great module. And I agree, assumption checks would be a great addition.

**Comment by mcfanda** [comment]
Version 2.3.0 has new plots for mixed models assumptions check
