### ISSUE TITLE
Variabele scaling options panel does not update after changing analysis focus

### ISSUE THREAD

**Issue by Gootjes** [gamlj/gamlj#105]
Steps to reproduce:
1. Have two GLM analyses in a jamovi file
2. Set the scaling of the continuous variables to standardized in analysis 1
3. Select analysis 2
The scaling options are still set to standardized, but the analysis 2 shows the output of unstandardized, and analysis 2 only updates after setting them "back" (they never were) to centered, and then setting them to standardized.

gamlj version 2.0.0, jamovi version 1.2.0

**Comment by mcfanda** [comment]
Yes, this should be fixed

**Comment by Gootjes** [comment]
I am pretty sure this was fixed? :)
