### ISSUE TITLE
simple effects do not working in GAMLj

### ISSUE THREAD

**Issue by hyunsooseol** [gamlj/gamlj#107]
Hi

I am trying to run simple effects with GAMLj module.  However, the following error message appears in screen;

Refine the model or the covariate conditioning(if any)

I attached "simple.omv" file
[simple.zip](https://github.com/gamlj/gamlj/files/4095082/simple.zip)
. 

Could you check it for me? 

Oh another question ^^ When do I expect to see SEM module in jamovi ?

Cheers

Seol

**Comment by hyunsooseol** [comment]
Oh it works now in ver.2.0.1 ^^ Thanks

**Comment by mcfanda** [comment]
Good to know, thanks for the message
