### ISSUE TITLE
Cluster-based scaling returns error: "arguments must have same length"

### ISSUE THREAD

**Issue by benminder** [gamlj/gamlj#112]
In GAMLj's "Mixed Models" and "Generalized Mixed Models" menus, selecting either "cluster-based centered" or "cluster-based standardized" scaling returns the error "arguments must have same length". No errors occur when selecting "centered", "standardized", or "none".

Perhaps the cluster-based options should be renamed to avoid any spaces? (e.g., "cluster-based-centered" or "ClusterBasedCentered").

This is from Jamovi 1.2.2 with GAMLj 2.0.4 on Windows.

Looking at the syntax, this works fine:

gamlj::gamljMixed(
    formula = Empowerment ~ 1 + LMX+( 1 | Team ),
    data = data,
    scaling = list(
        list(
            var="LMX",
            type="standardized")))

But this returns the error:

gamlj::gamljMixed(
    formula = Empowerment ~ 1 + LMX+( 1 | Team ),
    data = data,
    scaling = list(
        list(
            var="LMX",
            type="cluster-based standardized")))

**Comment by mcfanda** [comment]
Yes, good catch, thanks. It will be fixed (together with a couple of other small bugs) in next version 2.0.5 out tomorrow

**Comment by mcfanda** [comment]
The names of the scaling options are also fixed in the direction you suggested. For legacy, however, in the new version it will work with "cluster-based-standardized" (the new official name), "cluster-based standardized", the old version and "clusterBasedStandardized" (I like camel case :-) )
