### ISSUE TITLE
help with jamovi analysis on moderation

### ISSUE THREAD

**Issue by VALA360** [gamlj/gamlj#114]
I chanced upon a moderation analysis you did on exercise and age. I saw that your GLM produced a simple effect table that included the slope of the regression line at -1 SD, +1 SD AND the mean of the moderator variables. I did the same analysis but my own simple effect table generated doesn't show the slopes for the regression line at different SD units of the moderator variables.  
can anyone help out?

**Comment by mcfanda** [comment]
did you solve the issue?
