### ISSUE TITLE
Negative Binomial Distribution for Generalized Mixed Models?

### ISSUE THREAD

**Issue by benminder** [gamlj/gamlj#115]
Is there any reason that the Generalized Mixed Models menu doesn't feature a negative binomial option, but the Generalized Linear Model does? Could this option be added to the GMM section? Alternatively, could a negative binomial distribution be added to the custom distribution menu so that it could be specified there?

**Comment by mcfanda** [comment]
sure, good idea.

**Comment by N1X3L** [comment]
@mcfanda Thank you for considering this enhancement. I too would greatly appreciate the negative binomial option.

**Comment by mcfanda** [comment]
Negative binomial is now in 2.1.2, not yet released, but you can try it out if you install it from github
