### ISSUE TITLE
For recent version of jamovi running GAMLj: "jamovi-engine has stopped working"

### ISSUE THREAD

**Issue by R180** [gamlj/gamlj#116]
For recent versions of jamovi running GAMLj (e.g., jamovi 1.2.19),  If I attempt to run even the simplest GAMLj analysis (generalized linear model with 1 dv and 1 iv), I get the following errors: "jamovi-engine.exe has stopped working", "This analysis has terminated, likely due to hitting a resource limit".
(I'm using Windows 10. I've tried uninstalling then reinstalling GAMLj but that did not help. The problem is only happening with GAMLj. Other aspects of jamovi are working fine.

**Comment by mcfanda** [comment]
Hi
I've never seen this issue in the latest versions. I've just tried the module on a new Windows machine and no problem arose. Let me do some checks and I'll get back to you

**Comment by mcfanda** [comment]
Hi, it is not an issue of gamlj, even though it looks like that. Please read here https://forum.jamovi.org/viewtopic.php?f=6&t=826&p=2837#p2837
