### ISSUE TITLE
Feature request: Residuals analysis

### ISSUE THREAD

**Issue by Trebicky** [gamlj/gamlj#117]
Hi,

Thanks for the excellent package for jamovi.

Do you think it would be feasible to add residuals analysis?

I know jamovi cannot populate new columns with data from a given analysis (so far), but I am currently running an analysis, where mean values of my DV do not change with an increase of my IV. However, based on visual inspection of the produced figure, CIs are widening on one side of the graph. Therefore I suspect heteroscedasticity in my data. I would like to test this by analysing residuals, and I would prefer not to jump to R to do so.

Thanks!

**Comment by mcfanda** [comment]
that's definitely a good idea, I should get to it asap

**Comment by Trebicky** [comment]
I am glad you like it. Looking forward!

**Comment by asplundj** [comment]
I guess this is related to #102. I would also be very glad to see this enhancement

**Comment by mcfanda** [comment]
jamovi is rapidally  expanding its features in order to save models output, such as residuals and predicted values. In a few weeks those feature will be available and gamlj will implement them asap
