### ISSUE TITLE
continuous IV and a repeated measures continuous DV

### ISSUE THREAD

**Issue by vivalasocialpsy** [gamlj/gamlj#118]
Hi,
I want to run a Generalized Mixed Model on Jamovi with a continuous IV and a repeated measures continuous DV. However, it seems like we can only use categorical dependent variables. Is it possible to take a continuous variable as DV in the Generalized Mixed Model?

**Comment by mcfanda** [comment]
No, because if the DV is continuous, in the sense that it is quantitative and normally distributed, you can use Mixed Model
