### ISSUE TITLE
Feature request: Non-linear test

### ISSUE THREAD

**Issue by Trebicky** [gamlj/gamlj#119]
Hi,
Would it be possible to add non-linear options and model comparisons (e.g. linear vs exponential or logarithmic and squared)?

Thanks for a great job with gamlj!

**Comment by mcfanda** [comment]
Non-linear link functions are already implemented in the module. Model comparisons is in the oven, but it requires a bit of coding

**Comment by Trebicky** [comment]
Perfect! Thanks for your great work.

**Comment by mcfanda** [comment]
Hi, version 3 (in preview here: see readme in this repository) allows for model comparisons
