### ISSUE TITLE
bind frequency to Nmax as dependent

### ISSUE THREAD

**Issue by kornbrot** [gamlj/gamlj#121]
it looks great BUT
my data is iin format where freq has number of target responses and Nmax has numbeer of alternatiives
this could be entered as freq rows with  cat =1 and Nmax - freq rows with cat =0, where cat is the binary variable
in glmer ine can bind (freq,Nmax) as proprotion
is there any way one can do this in gamlj
i love jamovi - although exportingresults in EXCEL would also be nice
In admiration
Diana

**Comment by mcfanda** [comment]
this will be implemented in the next versions (the latest is 2.2.1).  Thx for the input, look for version 2.2.* > 1

**Comment by mcfanda** [comment]
Not really, we are thinking on an easy way to reshape your data before passing them to gamlj

**Comment by mcfanda** [comment]
this feature is implemented in version 3.2.7
