### ISSUE TITLE
Incorrect intercept estimate

### ISSUE THREAD

**Issue by matschmitz** [gamlj/gamlj#123]
The GLM intercept seems to be miscomputed as it differs when computed with _Regression/Linear Regression_ vs. _Linear Models/General Linear Model_ in Jamovi. All the other predictors are estimated correctly.

Jamovi: v.1.2.25
gamlj: v.2.0.5

Also, it would be super nice to have the ANOVA Omnibus test for the intercept as well!

This is an example:

![image](https://user-images.githubusercontent.com/37771001/90335084-65119a00-dfd2-11ea-987f-73e739e15829.png)

**Comment by mcfanda** [comment]
GAMLj center to their means the variable (by default, you can remove this in the options), so the intercepts are correct, but they give the expected value of the dependent variable for the independent variables at their means
