### ISSUE TITLE
GMM Poisson (overdispersion) missing

### ISSUE THREAD

**Issue by N1X3L** [gamlj/gamlj#124]
I'm using GAMLj v. 2.0.5 on jamovi v. 1.6.3.0, yet the Generalized Mixed Linear Models module does not offer the Poisson overdispersed model as expected.

![Poisson me](https://user-images.githubusercontent.com/58523957/93837785-17c9bd80-fc4d-11ea-9eae-b7f3ca5f79cc.png)

**Comment by mcfanda** [comment]
It will come :-)

**Comment by N1X3L** [comment]
Poisson (overdispersed) and negative binomial models were added to Generalized Mixed Linear Models in GAMLj v. 2.1.1. **Thank you so much!**

**Comment by mcfanda** [comment]
Hi, actually they are not there yet, so we should wait for the next version

**Comment by N1X3L** [comment]
Yes, my mistake, thank you. I was overly excited, and looking at the GLM screen, not the GMM. Very excited for the 2.1.2 official release!
