### ISSUE TITLE
GAMLJ Mixed effect freezes jamovi

### ISSUE THREAD

**Issue by Trebicky** [gamlj/gamlj#125]
Hi,

we just came across an issue with GAMLJ freezing up. We tried to set up a mixed-effect model with 11 covariates, two factors and two cluster variables from ~400 lines of data. Jamovi uses over 1GB of RAM and freezes up.

**Comment by mcfanda** [comment]
We're looking into the problem, thanks for sharing it

**Comment by mcfanda** [comment]
If you can, please send me (by email) the omv file so I can check on my computers

**Comment by Trebicky** [comment]
I would like to, however, these are confidential data I cannot share. But there is nothing particularly specific, only numbers and mostly short integers or numbers with no more than two decimal places. I guess it is just a sheer overkill of a model specified.

**Comment by jonathon-love** [comment]
yeah, the question we're trying to answer is whether this is a jamovi issue, or if "that's just how long it takes". if you have some R skills, you could settle the matter by running the analysis in an R session and seeing if it takes just as long.

cheers

**Comment by mcfanda** [comment]
Please use R lme4 command lmer() and see how it deals with your model. If you please, run also an anova() on the model, so we can see whether the last command is the one very slow
thanks

**Comment by Trebicky** [comment]
I'll try, but unfortunately not before the end of next week.

**Comment by mcfanda** [comment]
Does it work now?
