### ISSUE TITLE
Feature request: effect size for the intercept

### ISSUE THREAD

**Issue by matschmitz** [gamlj/gamlj#126]
Hi,

It would be really useful if we could compute the effect size (e.g., partial eta squared) for the intercept, just like SPSS does. The best case scenario would be to have an extra column indicating the partial eta squared in the Fixed Parameters Estimates table. This is an example of an SPSS output:
![image](https://user-images.githubusercontent.com/37771001/94413467-69a5a280-017b-11eb-8c83-b4e19ba7a450.png)
 I really want to recommend JAMOVI and the GAMLJ module in particular to my students for my stats course, but without the effect size for the intercept they will unfortunately have to stick with SPSS.

I hope this can be implemented.

Best

**Comment by mcfanda** [comment]
Hi, we did not include the partial eta squared for intercept because it is one of the most uninterpretable coefficient. By the way, how do you use this ES?

**Comment by matschmitz** [comment]
Is there still a chance you can include it? It would really be awesome!

It is the proportion of the variance explained compared to a model that predicts 0 (if I'm correct). In multiple regression, it is just the proportion of variance explained beyond the other fixed factors.

**Comment by mcfanda** [comment]
Hi, the forthcoming version 2.2.0 will feature the F-test and effect sizes for the intercept in the GLM (as per your request). In GLM, you'll find a new panel at the bottom of the input interface named "Options", then "Additional Info". If you flag "On intercept", you get a table with F, p, partial eta2, and omega for the intercept.  It will be out next week. Please check out if you find the same results than in SPSS, so I can see if there're problems
thx
mc

**Comment by matschmitz** [comment]
Amazing, thank you! I'm looking forward for the update.
