### ISSUE TITLE
New version (2.1.2) possible bug

### ISSUE THREAD

**Issue by brresearcher** [gamlj/gamlj#135]
The GLZM module can't compute, it states "The analysis has terminated, likely due to hitting a resource limit", although the GLM module is working fine.

I tried reinstalling previous versions of jamovi (1.6.7, 1.6.8), and the current (1.6.9), did not work.

![image](https://user-images.githubusercontent.com/76265653/102699300-64a83a80-4222-11eb-9098-f11771871733.png)

**Comment by brresearcher** [comment]
I installed an older jamovi version (1.2.27) and then an older GAMLj module version (2.0.5) and it ran the analysis perfectly in the GLZM, it is likely a problem with the current version (2.1.2)

**Comment by mcfanda** [comment]
Bug found, version 2.2.0, forthcoming in a few hours, solved it. Please check it out. Thanks for spotting it.

**Comment by brresearcher** [comment]
Thanks a lot! Tomorrow I'm back to work and gonna check it out!

**Comment by brresearcher** [comment]
It's working just fine! Thanks a lot!
