### ISSUE TITLE
Different results in gamlj and base R for moderation model

### ISSUE THREAD

**Issue by covert-koala** [gamlj/gamlj#141]
Racking my brain for the longest time over discrepant main effects in gamlj and R. I have a moderation model with a few continuous predictors and one trichotomous predictor. There is also an interaction between some continuous predictors and one continuous by trichomotous interaction. When specifying this using the lm function in R, I was getting pretty much identical interaction effects as produced by gamlj but wildly different main effects. I isolated the problem to the inclusion of the continuous * trichotomous interaction in R. I can include other continuous * continuous interactions and get harmonious results, but just not the continuous * trichotomous. I confirmed that the trichomotous variable is set to factor with three levels in R, and the same variables are centered in both approaches, so not sure why this is happening. Which package is correct?

Here's the R code:
ps_interaction <- lm(PS ~ 1 + dob + CR + chronicity + severity_trichot + CR:dob + CR:chronicity + CR:severity_trichot, data=CRdata)

and the gamlj:
ps_interaction2 <- gamljGLM(formula = PS ~ 1 + dob + CR + chronicity + severity_trichot + CR:dob + CR:chronicity + CR:severity_trichot, data=CRdata)

So, to reiterate, the effects for all the interactions are (more or less) in agreement, whereas dob, CR, chronicity, and severity_trichot (both groups 1 and 2 against reference 0) are not. If I remove the CR: severity_trichot interaction from both approaches, identical results for all effects!

Thanks,
Umi

**Comment by mcfanda** [comment]
HI
could you please share the output of the analyses?

**Comment by covert-koala** [comment]
> HI
> could you please share the output of the two analyses and the output of the R command `contrasts(severity_trichot)`?

Absolutely. Here's the output of the contrasts command:
..   1 2
0   0 0
1   1 0
2   0 1

**The output of gamlj is here:**
[gamlj_output.pdf](https://github.com/gamlj/gamlj/files/5743903/gamlj_output.pdf)

**The R output is as follows:**
Call:
lm(formula = PS ~ 1 + dob + CR + chronicity + severity_trichot + 
    CR:dob + +CR:chronicity + CR:severity_trichot, data = CRdata)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.70330 -0.48095 -0.09275  0.52296  1.97089 

Coefficients:
                       Estimate Std. Error t value Pr(>|t|)    
(Intercept)          -0.8381817  0.1921440  -4.362 3.21e-05 ***
dob                   0.0029083  0.0100884   0.288   0.7737    
CR                    0.0201183  0.0210307   0.957   0.3411    
chronicity           -0.5342125  0.2444510  -2.185   0.0313 *  
severity_trichot1    -0.0097415  0.2497028  -0.039   0.9690    
severity_trichot2    -0.1586244  0.2193943  -0.723   0.4714    
dob:CR                0.0011028  0.0008801   1.253   0.2132    
CR:chronicity        -0.0590040  0.0231846  -2.545   0.0125 *  
CR:severity_trichot1  0.0419372  0.0238308   1.760   0.0816 .  
CR:severity_trichot2  0.0411885  0.0234701   1.755   0.0824 .  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.8082 on 97 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.4989,	Adjusted R-squared:  0.4524 
F-statistic: 10.73 on 9 and 97 DF,  p-value: 2.107e-11

**Comment by mcfanda** [comment]
The results are all correct, but they show different models. GAMLj center the continuous variables to their mean, and set the categorical variable to contrasts that are centered to 0 and compare one reference group to all the others. 
When you run your model in R, you're not estimating the "main effects" of your variables, because severity_trichot is not centered, thus, what you get in R are the simple effects of all your variables estimated for severity_trichot=0. This is not a software issue, it like the linear model works. 
If you want to have gamlj give the same results to R (but that is not the usual goal), you need to set the contrasts for severity_trichot as "dummy", provided that the reference group is the same.
If you want to get in R the same results as in GAMLj, you need to center severity_trichot to zero. 
Please notice that if you have in mind a "classical" analysis, meaning main effects and interactions, GAMLj gives you the right results

**Comment by mcfanda** [comment]
here more info https://gamlj.github.io/rosetta_contrasts.html

**Comment by mcfanda** [comment]
In R, if you set the contrasts of severity to 
![image](https://user-images.githubusercontent.com/5815641/103174690-8cbc1d00-4864-11eb-889a-e258d035830e.png)
you'll get the same results as in GAMLj (as long as the other variables are centered)

**Comment by covert-koala** [comment]
Excellent- thank you for the thorough explanation. I changed the coding to dummy in gamlj, and the results were consistent with R. I changed to contrast coding in R, and the results were consistent with gamlj simple coding. All is well!

Now I can report results with confidence. Happy New Year!
