### ISSUE TITLE
Contrast coefficient tables for "Simple" and "Deviation" are mixed up with each other

### ISSUE THREAD

**Issue by benminder** [gamlj/gamlj#142]
When opening the Contrast Coefficients table, the provided coefficients don't always match the selected factor coding. 

In particular, the coefficients for "simple" and "deviation" appear to be mixed up with each other. The verbal description of the contrasts are correct in each case, and the proper analyses are being conducted, but the coefficients listed in the tables are crossed with each other. 

From what I can tell, the coefficients for the other coding options are fine. 

My students noticed this when learning gamlj in stats class! :)

**Comment by mcfanda** [comment]
HI, 
I've checked and I cannot see the issue. Compared with https://stats.idre.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/#SIMPLE, for instance, the table in gamlj returns the correct coefficients both for simple and for deviation.  Could you provide an example of the bug?

**Comment by benminder** [comment]
Whoops, I think you're right. We must have gotten confused about how simple coding works, as the tables are indeed aligned with the site you referenced. Sorry for the false alarm!

**Comment by mcfanda** [comment]
Well, that happens to me all the time. Thanks for checking
