### ISSUE TITLE
Random Effects Confidence Intervals

### ISSUE THREAD

**Issue by AndrewGovus** [gamlj/gamlj#147]
Hi,

Thanks very much for a very accessible mixed model module in Jamovi. It's really been a game changer for me introducing people to mixed modelling. I wondered if it hasn't been added already (or is in the pipeline), is it possible to set output to report the confidence intervals of the random effects reported in the summary table as well? These are often very useful in my discipline. I can calculate these in R using lmer or nlme, but I wondered if it is easy to add the package?

Thanks again for your efforts on producing a great package.

Andy

**Comment by mcfanda** [comment]
Good idea, I'll put it there for next version

**Comment by mcfanda** [comment]
I guess you referring to confidence intervals for the estimated variances of the random coefficients. Right?

**Comment by mcfanda** [comment]
Although the confidence intervals for variances are very tricky, so this issue requires some thoughts, because we do not want to report stats that may be misleading for users

**Comment by mcfanda** [comment]
It's in the next version
