### ISSUE TITLE
Mixed-effects - Random effects correlation option not reflected in output

### ISSUE THREAD

**Issue by juju-bowow** [gamlj/gamlj#152]
Hi there, 

Firstly, I would like to thank the developer(s) for their hard work and effort in providing such an exceptional module for JAMOVI.

Jamovi: 1.8.1.0
gamlj: 2.4.5

Steps to reproduce this issue:

1) Run two identical Generalized Mixed Models (I've troubleshooted this issue using the 'schoolexam' data set, provided with Gamlj, as well as my own dataset).

2) Set one to have 'Not correlated' random effects. The 'call' in Model Info output should (i understand) read something like dv ~ iv1 + iv2 + (0 + iv1 | ID), and it does.

3) Set one to have 'Correlated' random effects. The 'call' in Model Info output should (i understand) read something like dv ~ iv1 + iv2 + (1 + iv1 | ID), or dv ~ iv1 + iv2 + (iv1 | ID). However, instead the call reads the same as 2)

4) Note that 3) provides identical jamovi output as 2), though I would expect that AICs and other values in Model Info table would differ. Running the two models in lme4 with the schoolexam data set provides different outputs for each model.

Please let me know if any further information could be of use.

**Comment by mcfanda** [comment]
Hi, I cannot reproduce the issue. With `schoolexam`, moving from "Correlated" to "Not correlated" does change the call, and the results (AIC goes from 5662.070 to 5661.010, not much, but shows that the models are different).
On which OS are you working?

**Comment by juju-bowow** [comment]
Hi Marcello, 

Thanks for your reply. 

After playing with the options further in response to your reply, I have determined that this issue resulted from my misunderstanding of how to use the Random Effects boxes in Gamlj.

I included only _math | school_ in the Random Coefficients box, thinking that this should give the equivalent output as _lme4::glmer(pass ~ 1 + math + (math | school)_, where models with random slopes automatically model random intercepts as well, and so the Intercept "1+" is included implicitly. When doing so, the Effects Correlation options do not change the model (see video capture attached if interested [10MB]).

However, when including _both_ components _Intercept | school_ and _math | school_, I get the same AICs as you do above, and the models change as expected when different Effects Correlation options are selected.

**Proposed resolution:**
I (and others) must remember to include _both_ features of the random effects in the model, as random intercepts are not included implicitly when random slopes are included.

My apologies for any confusion caused by this issue!
Thanks again for creating and maintaining such a great JAMOVI module!

[Recording.zip](https://github.com/gamlj/gamlj/files/6389246/Recording.zip)

**Comment by mcfanda** [comment]
Yes, the specification of each random component is crucial. I'm not in favor of implicit specifications (like the (x|ID) notation in lmer() ) because they may be confusing for users. In jamovi, furthermore, specifying one random coefficient activates the estimation of the model. If we put an implicit intercept, the model would be estimated before the user finishes setting up the model.

**Comment by juju-bowow** [comment]
Ahh I see. I agree that these are each very good reasons for Gamlj to require specification of each random component.

I'll close this comment now. Hopefully it will be of use to other users as well.

Thanks again Marcello! :)
