### ISSUE TITLE
Does the Mixed Model within gamlj assume that the dependent variable is approximately continuous?

### ISSUE THREAD

**Issue by R180** [gamlj/gamlj#176]
The Mixed Model within gamlj will run and produce output even when the dependent variable is categorical. Is this a bug (should gamlj disallow this)? Or does the Mixed Model properly accept a categorical dependent variable?

**Comment by mcfanda** [comment]
`Mixed model` is for continuous dependent variables. One can use `generalized mixed models` for other types of variables. It is not a bug: the software does what the user wants to do, it is up to the user to choose the right model depending on their data.
