### ISSUE TITLE
'distribution' and 'link function' 

### ISSUE THREAD

**Issue by vliborio** [gamlj/gamlj#178]
Good morning everyone, this is my first question in github and maybe quite simple but I'm trying to launch a GLM in Jamovi and I was wondering when you choose 'custom model', what's the difference between 'distribution' and 'link function'?
Also, I'd like to know when you've launched a GLM and in the AIC or BIC appears 'Inf', what does it mean?

Thanks in advance and congratulations on the software, it's amazing!

**Comment by mcfanda** [comment]
Hi,
the repository issues are meant to suggest bugs and improvement of the package. For statistical questions regarding the analyses and their interpretations, I'd suggest to post a question in the jamovi forum https://forum.jamovi.org/, where there are many people willing to assist you and discuss these topics.
cheers
mcfanda
