### ISSUE TITLE
CI for total effect are the same for normal and bootstrap methods

### ISSUE THREAD

**Issue by pa0** [gamlj/gamlj#179]
We noted that the confidence intervals for the Total effect have the same values for the method based on the normal distribution and the bootstrap method. Shouldn't it be for bootstrap they should differ depending on the run of the analysis?

**Comment by mcfanda** [comment]
Hi
what do you mean with "Total effect". Are you sure you're working on GAMLj? Maybe you are on jAMM?

**Comment by pa0** [comment]
You are right - this is in the jAMM module. Sorry for the lack of precision in describing the issue.

**Comment by mcfanda** [comment]
Please post it on jAMM repository
