### ISSUE TITLE
Effect of X - continuous variable on Y - continuous variable 

### ISSUE THREAD

**Issue by zpapadakis** [gamlj/gamlj#198]
Hi, 

I am trying to get some help on the following research design. I want to know what is the effect of X variable on Y, when both variables were measured in 4 different times using the same participants. 

My understanding is that GAMLj is the best analysis to do. I have my data in long format so my connection is how do I enter the data in the Jamovi. 

At the moment I have them as follows:

y in the Dependent variable box, subjects in the Cluster variable box, time in the factor variable box, and my inquire is where do I put the x variable. Do I use the Covariate box?

also for the fixed do I need to do the interaction between time and X variable? On top of that for the random effects should I pick ony the intercept -subjects or the X-athlete too?

Much appreciated

**Comment by mcfanda** [comment]
Please referto http://forum.jamovi.org
