### ISSUE TITLE
BUG - GAMLj 3.0.9 Generalized linear models - Changing distribution

### ISSUE THREAD

**Issue by 06breno** [gamlj/gamlj#206]
In previous versions when changing the distribution of the model it removed the dependant variable from the analysis, now it does not do that. As a result, the "system" does not re-calculate for the new distribution as it should and continues showing the values estimated for the previous
[Report GAMLj3.pdf](https://github.com/gamlj/gamlj/files/13030453/Report.GAMLj3.pdf)

**Comment by mcfanda** [comment]
There must be something going on, because in my tests it does remove the dependent variable. Could you send some more information to check this issue?

**Comment by mcfanda** [comment]
Ok, you mean when you use "Custom" distribution.

**Comment by mcfanda** [comment]
Great. I fixed it: now the dep var is removed only when the "custom" model, or any other model type. Inside "Custom", changing the distro or the link does not remove the dep var, but it updates the results. 
 thanks a lot for your help
(it may need a couple of days to see the update in jamovi library, it will be version 3.1.0)

**Comment by 06breno** [comment]
Thank you very much!
