### ISSUE TITLE
jAMM bootstrap error?

### ISSUE THREAD

**Issue by c07411994** [gamlj/gamlj#211]
Hello everyone, a few days ago, I attempted to run the jAMM module on a model with one independent variable (IV), one dependent variable (DV), and three mediators. However, I was unable to obtain bootstrap standard error (se) results and encountered an error message stating "!is.null(BOOT) is not TRUE." I tried repeatedly, but the error persisted.

I also attempted to analyze the same data using the pathj module. In this case, I was able to successfully obtain bootstrap se results.

Does anyone have experience with this error and know how to resolve it? I would be grateful for any assistance in resolving this issue.

Thank you!

P.S. I am using jamovi version 2.4.11 and jAMM version 1.2.3.

**Comment by mcfanda** [comment]
would you mind posting this issue in the jAMM repository, this is for GAMLj, which is a different module. Thanks

**Comment by c07411994** [comment]
Thank you for your response. I apologize for posting this question here. I clicked on the link under "Comments?" from the jAMM page, thinking that the two modules share the same discussion forum.
