### ISSUE TITLE
EMM for unbalanced data

### ISSUE THREAD

**Issue by hiswy** [gamlj/gamlj#220]
First of all, I would like to thank you for the prompt answers to my previous inquiries. 
They have helped me greatly.

While running some analyses,
I noticed that the Factorial ANOVA [basic] provided the EMM calcuation for unbalanced data [by unchecking equal cell weights].
GAMlj module also provides the Estimated Marginal Means but I could not find the similar option as mentioned above. 
Would be possibl to add an option for an unbalanced data?

Thank you sincerely in advance.

**Comment by mcfanda** [comment]
Well, this is not very high in the priority list. When you estimate your model with GAMLj, and you (really) need the estimated marginal means weighted by cells sample size, you can always run the same model with jamovi ANOVA or ANCOVA to obtain the weighted marginal means. I try to reduce redundancy across modules and commands
