### ISSUE TITLE
Image Export is Grey Box

### ISSUE THREAD

**Issue by N1X3L** [gamlj/gamlj#222]
Exporting the results plot of a GLM as either an SVG or PNG in GAMLj3 (v. 3.1.6), used within Jamovi (v. 2.4.11 from Flathub), produces a grey box with the number "1" in the upper left corner.
<img width="600" alt="eg of Grey 1 Box" src="https://github.com/gamlj/gamlj/assets/58523957/85e0a4ce-d14a-4e10-a819-8cbccbb5045d">

**Comment by N1X3L** [comment]
Follow up, I just conducted the same analysis in GAMLj (v. 2.6.6) and it exported the results plot as expected. I thought that information may be helpful in troubleshooting this.

**Comment by mcfanda** [comment]
Thanks a lot. I will fix it in the next version

**Comment by N1X3L** [comment]
Just letting you know that I updated to v. 3.2.0, but unfortunately plots don't seem to be working at all now. Please let me know if I may provide any further information that might be diagnostic. Thank you!

**Comment by mcfanda** [comment]
Well, I cannot reproduce the issue (plots work fine). In which operative system are you? Can you share an example?

**Comment by N1X3L** [comment]
Apologies, I should've tested further. It does work unless I select the "Observed scores" option. If that option is selected, no plot generates.

**Comment by mcfanda** [comment]
We ll fix it pronto. Thanks for the help

**Comment by mcfanda** [comment]
also here I cannot reproduce the issue. Can you specify which model you are testing, which kind of variables and what plot?

**Comment by N1X3L** [comment]
Thank you for following up! Try this, and attempt graphing a plot with "Observed scores" selected.
![eg_GAMLj3](https://github.com/gamlj/gamlj/assets/58523957/8284dfdc-9135-4675-9d82-2e77fe0d81a4)

**Comment by mcfanda** [comment]
fixed, it was a memory issue.

**Comment by N1X3L** [comment]
Thank you so much!
