### ISSUE TITLE
Availability of gamlj3 in the Jamovi library?

### ISSUE THREAD

**Issue by mdaamen** [gamlj/gamlj#224]
Hi,

thanks for this great toolbox, and the accompanying webbook in progress.

Your Jamovi blog entry from October 2023 gave me the impression that gamlj3 was already available in the Jamovi library. Yet, both my installed Jamovi and the website only show me the previous version 2.6.6. 

Do I miss something, or does only the install in R work at the moment?  

Best wishes,

Marcel

**Comment by mcfanda** [comment]
Please install jamovi "current" version, there you find GAMLj3 in the library. jamovi current is always the best choice. "Stable" is to guarantee usability to old computers or legacy OS's. "current" is pretty stable.

**Comment by mdaamen** [comment]
Thank you, indeed, I used the "solid" version, as it was "recommended for most users". Now it works!

Best wishes, Marcel
