### ISSUE TITLE
Odds ratios for GLMs

### ISSUE THREAD

**Issue by stats-matt** [gamlj/gamlj#232]
When running something like a Poisson model, the checkboxes still say "Odds ratio" which might be confusing - it might be better to switch to incidence rate ratios.

**Comment by mcfanda** [comment]
Hi
I see your point, it's just a bit of a trouble to change the checkboxes labels when different models are selected. Maybe the term  `exp(B)` would be more appropriated across models. I'll work something out.
thanks for the feedback

**Comment by mcfanda** [comment]
ok, it will be in the next version (3.2.4)

**Comment by stats-matt** [comment]
Thanks - and yep, I think exp(B) is a nice option.
