### ISSUE TITLE
Suggested options for quasi families. Suggested option for binomial regression data formats

### ISSUE THREAD

**Issue by RegalPlatypus** [gamlj/gamlj#233]
I routinely use generalized linear models to model proportions at my company. In R, binomial data can entered either as 0/1 data or you can cbind(success/failures), allowing for replicated scores of proportional data. Often these models display overdispersion so I resort to quasibinomial (or quasipoisson families for count data). 

I perform these in R without issue, but I have some direct reports who are not familiar with R and really benefit from zero-programming-required interface of Jamovi. Is there any chance you could incorporate these options?

- The inclusion of quasibinomial and quasipoisson families?
- The ability to enter response variables that are either 0/1 in a single column, or two columns corresponding to a column of successes and a column of failures? 

Thanks for your hard work!

**Comment by mcfanda** [comment]
In GAMLj3 you have "Poisson (overdispersion)" which is equivalent to glm(...,family=stats::quasipoisson()). I can add `quasibinomial) without problem (next version).

As for the `cbind()` possibility, unfortunately the whole module structure is not compatible for this kind of data input. However, I am working on a solution for this because I realize that many users would benefit from it. However, it would not be in the next version.

**Comment by mcfanda** [comment]
you can send me a reproducible example so I can check it out in detail

**Comment by mcfanda** [comment]
please check the new version 3.2.7. I implemented the cbind() kind of interface. Check it out if works as intended

**Comment by RegalPlatypus** [comment]
Thanks for continuing to improve this!
I'm toying around in 3.2.7, but it isn't immediately apparent how I should input the dependent variable in a cbind(successes, fails) format. If you can give me that initial push, I should be able to play around and give some useful feedback.

Thanks again!

**Comment by RegalPlatypus** [comment]
I played around a bit today and it seems to be functioning as it should! Thanks for making this implementation! This is the bread and butter of the analyses my team does, so having this in Jamovi will really make analysis much more accessible to some of my team members who are less competent in R.

I look forward to the update with a quasibinomial family option in a later update!
