### ISSUE TITLE
Message - could not find function "reject - on Jamovi when trying multilevel modeling

### ISSUE THREAD

**Issue by DimitriosLA** [gamlj/gamlj#234]
Hello, I need help ! :)

I am trying to conduct a multilevel modeling analysis with mixed models on Jamovi, using the WVS survey.
But I always get his message : could not find function "reject"
Same applies when I try with another survey !

What can I do ?
Thank you very much !!
Dimitrios

**Comment by mcfanda** [comment]
Hi
check if you have updated both jamovi and gamlj. Gamlj does not use any function called "reject", so it must be some issue with jamovi version.
