### ISSUE TITLE
Method for including offsets in Poisson regression

### ISSUE THREAD

**Issue by estebanv-csde** [gamlj/gamlj#236]
I would like to use the gamlj module to help teach a tutorial on Poisson regression. However, the example data that I use is aggregate data, for which an offset would be required to properly implement the Poisson regression. If I were to analyze this in R I could implement the following code:

`glm(y ~ x + offset(log(population.size)), data = my.data, family = poisson)`

However, to my knowledge the point-and-click interface for the gamlj module does not contain a method for incorporating such an offset term. Am I merely looking in the wrong place, or is this feature not available yet? It would be great if such a feature could be made available as it would render the gamlj module (and jamovi) as more useful for the analysis of aggregate data!

Thanks for your hard work!

**Comment by mcfanda** [comment]
Hi, if you use GAMLj3, you can include the offset in the dedicated field. If you want to pass the equivalent of `offset(log(population.size))`, simply compute a new variable `logpop` as `LN(population.size)` and use it as the offeset
![image](https://github.com/gamlj/gamlj/assets/5815641/296a606b-8c77-4bc3-b28a-39486cab748f)
