### ISSUE TITLE
Fail of model convergence GLMEM GAMLj3

### ISSUE THREAD

**Issue by Elislobra** [gamlj/gamlj#242]
Good morning, 

I am doing a GLMEM with GAMLj3 library. I am modelling the acceptance rate (0,1) with factors: effort level, reward level and stim_condition, and subject as a random factor. I ran the model and it does not converge when I use GAMLj3 library. I tried also with GAMLj (version 2) and the model does converge. I was wondering if it is because in the new version the optimizers are not included (example: bobyqa), if that is the case, is there anyway to add them manually in GAMLj3 (I would prefer to use the new version due to the post-hoc comparison option). Thanks in advance, 

Elisa.

**Comment by mcfanda** [comment]
Hi,
that's strange because GAMLj3 uses the same optimizers of GAMLj, only newer versions of the underlying R packages. Could you share an example when the issue happens (also via email if you prefer)

**Comment by Elislobra** [comment]
Hello, finally the model converged, I don't know exactly what happened. I have a second doubt, it is normal that if I rerun a model, I open another jamovi window I import the same database and I do exactly the same analysis (same factors, covariates, random factors, posthoc, etc), the results are different (different p-values, factors that before were not significant now they are and the inverse). I have repeat a third time and it is also different from the first and second. Fixed Effects Omnibus test, parameter estimates, posthoc, al different.

**Comment by mcfanda** [comment]
no, it is not normal. Actually, I have never seen this behavior. Could you share a reproducible example?
