### ISSUE TITLE
GLM Mediation module doesn't run

### ISSUE THREAD

**Issue by Dangbigo** [gamlj/gamlj#247]
I tried using window version 2.5, but the GLM Model doesn't run. 
It worked fine around October last year, which is strange. Could you help me resolve this issue?

<img width="802" alt="jamovi" src="https://github.com/gamlj/gamlj/assets/169887313/0a91d265-5d1b-4d36-9a82-ddc1871f433b">

Other analyses work fine, but only the gamlj module is affected. 
I try version 2.3 and 2.5, but the gamlj module doesn't run. 
My professor is using a Mac OS and has no issues with the gamlj module, but I'm using Windows, and I'm experiencing problems.

**Comment by mcfanda** [comment]
Hi, do you mind sending this issue to jamm, which is the module you are referring to. This would help better handling the fixing process

**Comment by Dangbigo** [comment]
Hi, Would you spend link for jamm? 

thank you.


-----Original Message-----

**Comment by mcfanda** [comment]
https://github.com/jamovi-amm/jamm
