### ISSUE TITLE
dependency ‘margins’ is not available

### ISSUE THREAD

**Issue by allefeld** [gamlj/gamlj#248]
I tried installing GAMLj3 in R using `devtools::install_github("gamlj/gamlj")`, but the installation fails:

````
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/RtmpalrI34/remotes41c737455a9b/gamlj-gamlj-0211570/DESCRIPTION’ ...
─  preparing ‘GAMLj3’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘GAMLj3_3.3.0.tar.gz’
   
Installing package into ‘/home/ca/Store/R’
(as ‘lib’ is unspecified)
ERROR: dependency ‘margins’ is not available for package ‘GAMLj3’
* removing ‘/home/ca/Store/R/GAMLj3’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpalrI34/file41c71ea18902/GAMLj3_3.3.0.tar.gz’ had non-zero exit status
````

I'm on Debian 12.5 and am using [the official R packages for Debian](http://cloud.r-project.org/bin/linux/debian). They have recently been updated to version 4.4.0, so maybe that is the problem.

However, looking up [`margins` on CRAN](https://cran.r-project.org/package=margins) leads to this message:

![image](https://github.com/gamlj/gamlj/assets/1738353/bf063637-8e09-453f-a866-d0c39d27f37e)

This sounds like `margins` isn't just not yet ready for 4.4, but has been removed indefinitely.

**Comment by mcfanda** [comment]
Thanks for mentioning it. I'll prepare a version without margins in a few days

**Comment by mcfanda** [comment]
Hi, the new version in master does not depend on margins anymore. Please try this one and check it out

**Comment by allefeld** [comment]
I just tried and it installs and runs perfectly, thanks!
