### ISSUE TITLE
Request for custom contrasts

### ISSUE THREAD

**Issue by srk7774** [gamlj/gamlj#253]
Hello, this package is one of the best with all possible options required. However, if a factor has three levels, is there any way to specify a customer contrast like this: factor_A{1, -1, 0}#factb in simple effects?

**Comment by mcfanda** [comment]
custom contrast are not implemented in the module. However, among the contrasts available you can find the one that suit you. 
As for your example, it is not clear what is the contrast that you need

**Comment by srk7774** [comment]
Say I am running a 3 x 2 x 2 between subject factorial design. These factors are facta, factb, factc. Now I want to check the interaction between facta{0 1 -1} and factb at different levels of factc. Suppose, facta has three types of coaching (no coaching, inhouse coaching, outcampus coaching). Now I want to test interaction between two coching levels and factb at the levels of factc. 
[table21.1_keppel_3way_pg466.txt](https://github.com/user-attachments/files/15802307/table21.1_keppel_3way_pg466.txt)

I am also attaching the datafile. 

library(phia)
fit = aov(dv ~ facta*factb*factc, data = data)
custom1 <- list(facta=c(0, -.5, 0.5))
testInteractions(fit, custom=custom1, fixed="factb", adjustment="none", across="factc")

Refer to this excellent article:
https://bcdudek.net/3wayanova/3way_factorial_Rmarkdown.html#way-factorial-design.-a-completely-randomized-between-subjects-factorial-design

Refer to this part:
6.4 Contrast Analyses in factorial designs using phia

**Comment by mcfanda** [comment]
Hi
Even though gamlj is not meant to estimate custom contrast, you can get the results you want using non-custom contrasts.

As for the problem you mentioned:  Assume facta levels are a1, a2, a3, factb levels are b1,b2,b3  and fatc levels are c1 and c2. You want to estimate the custom contrast c(0, -.5, 0.5), which is simply the difference between a2 and a3. So, you need to select a coding that gives you that contrast. You can choose "Repeated" in Factor Coding for facta.

You will see that in the parameter estimates table there will be a line with "Effect" equal to "a3-a2". That is your contrast of interest.

If you now want  to check the interaction between facta{0 1 -1} and factb at different levels of factc, go to simple effects, set facta as simple effect variable, factc and facb as moderators (in this order to replicate your R code) and look at the Simple Interaction - Parameter Estimates. You get the test and the p.value for the interaction contrast facta*factc. The ones with (a3-a2) labels are the tests you are interested in.
 
In general, here is a help page that shows how to exactly replicate the results in Dudek's page in [jamovi GAMLj](https://gamlj.github.io/rosetta_simpleint.html). I always try to test the module against some reproducible methods.

**Comment by mcfanda** [comment]
At the end I decided to implement custom contrasts in GAMLj3 after all. Now (since version 3.3.2) one can specify custom codes for contrasts and do all sort of analyses with them. See an [example here](https://gamlj.github.io/glm_example3.html). The new version is coming out next week ([preview here](https://github.com/gamlj/gamlj/tree/Version.3.3.2)

**Comment by srk7774** [comment]
This is an amazing feature and thanks for taking the time to implement it. I would test this feature once the update is released.
