### ISSUE TITLE
Issue on Generalized linear models (Gamlj v 3.3.1)

### ISSUE THREAD

**Issue by 06breno** [gamlj/gamlj#255]
Hi, I found a bug when changing dependent variables on the Generalized linear models, the second variable I try to add using the arrow simply disappears. It happened on Linear distribution and on Custom as well, I haven't tried the others.

I was using jamovi 2.5.4 but just ran with 2.5.6 and got the same issue.

Please see attached file for step-by-step.

Thanks. 

[Generalizes Linear Models Bug.pdf](https://github.com/user-attachments/files/15841712/Generalizes.Linear.Models.Bug.pdf)

**Comment by mcfanda** [comment]
It seems like this is the correct behavior. I GzLM you need one dependent variable.

**Comment by 06breno** [comment]
But the new variable does not go to the analysis, nor the previous is removed. The new variable I try to add just disappears from the module, like it doesn't exist.

**Comment by mcfanda** [comment]
Ok, now i see what to mean. It ll be fixed in next version. Thanks for the feedback

**Comment by 06breno** [comment]
Thanks a lot!

**Comment by mcfanda** [comment]
fixed in version 3.3.2, coming out in a few days
