### ISSUE TITLE
Request for solutions for GLM Mediation model error : due to hitting a resource limit

### ISSUE THREAD

**Issue by jhpeter84** [gamlj/gamlj#256]
Hello, 
I faced a problem when using GLM mediation model, and hope anyone suggest any solutions fot it. 
① It worked until putting a variable into both Dependent variable and Mediators. However,
② the problem appears after putting a variable into Covariates, showing 
'This analysis has terminated, likely due to hitting a resource limit'. 
I found that the Cloud ver. works for the above with no problem, but I really want to fix it. 
(I tried to use Jamovi ver. 2.5.6(the latest) and ver. 2.3.28(solid),  windows x64) 

captured image for '① 'above
![image](https://github.com/gamlj/gamlj/assets/172868164/7341dc5e-b08a-4850-b686-6ccf687edb9f)

captured image for '②'above
![image](https://github.com/gamlj/gamlj/assets/172868164/8b6bba0d-2925-42af-8f2e-6b164dc65303)

**Comment by mcfanda** [comment]
Hi,
there is a problem in windows with some characters (font types). I have difficulty solving this issue because it does not appear in linux (which I use). Would you mind sharing a .omv file so I can check it?

**Comment by hyunsooseol** [comment]
Hi
Try renaming the variables to English instead of Korean and try analyzing it.

**Comment by mcfanda** [comment]
Yes, I think that renaming the variables will work. However, if you can send an example with the original variable names we can try to solve the issue in general.
