### ISSUE TITLE
Bug: Simple Effects producing "unused argument (wts=wts)" error

### ISSUE THREAD

**Issue by njschweitzer** [gamlj/gamlj#267]
Using GAMLJ3 3.3.7 and Jamovi 2.6.2 (also in 2.6.0). Using GAMLJ3 to run a basic 3-way ANOVA via General Linear Model that I've run many times before without issue. When adding simple effects (using any combination of the variables), I get a "unused argument (wts=wts)" error. This has happened on several other datasets as well. 

![image](https://github.com/user-attachments/assets/4c859684-3016-4e69-948b-dd2267fb8929)

**Comment by mcfanda** [comment]
Yes, in 2.6.2 there is an conflict with other modules and the underlying R package. We sort it out very soon

**Comment by mcfanda** [comment]
Could you provide an example of the issue (.omv file), and let us know the operative system you're working on?
thanks

**Comment by mcfanda** [comment]
Please check out version 3.3.8 for a fix of this issue. Thanks a lot for reporting it.
