### ISSUE TITLE
Grouped Logit and Probit

### ISSUE THREAD

**Issue by srk7774** [gamlj/gamlj#269]
Is there any way that we can do grouped logit or probit as we do with stata.

https://www.stata.com/support/faqs/statistics/logistic-regression-with-grouped-data/

This is an example from basic Econometrics by Gujarati (Exercise 15.16, Table 15.24), I rearranged the data by creating "Counts" and "Y" to create a binary outcome variable. 

To study the effectiveness of a price discount coupon on a six-pack of a soft drink, Douglas Montgomery and Elizabeth Peck collected the data shown in Table 15.24. A sample of 5,500 consumers was randomly assigned to the eleven discount categories shown in the table, 500 per category. The response variable is whether or not consumers redeemed the coupon within one month. 
a. See if the logit model fits the data, treating the redemption rate as the dependent variable and price discount as the explanatory variable.
b. See if the probit model does as well as the logit model.

X	N	Counts	Y
5	500	100	1
7	500	122	1
9	500	147	1
11	500	176	1
13	500	211	1
15	500	244	1
17	500	277	1
19	500	310	1
21	500	343	1
23	500	372	1
25	500	391	1
5	500	400	0
7	500	378	0
9	500	353	0
11	500	324	0
13	500	289	0
15	500	256	0
17	500	223	0
19	500	190	0
21	500	157	0
23	500	128	0
25	500	109	0

. logit Y X [fw=Counts]

Iteration 0:   log likelihood =  -3811.128  
Iteration 1:   log likelihood = -3375.8241  
Iteration 2:   log likelihood = -3375.6653  
Iteration 3:   log likelihood = -3375.6653  

Logistic regression                                     Number of obs =  5,500
                                                        LR chi2(1)    = 870.93
                                                        Prob > chi2   = 0.0000
Log likelihood = -3375.6653                             Pseudo R2     = 0.1143

------------------------------------------------------------------------------
           Y | Coefficient  Std. err.      z    P>|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
           X |   .1357274   .0049571    27.38   0.000     .1260117     .145443
       _cons |  -2.084754   .0803977   -25.93   0.000    -2.242331   -1.927178
------------------------------------------------------------------------------

. probit Y X [fw=Counts]

Iteration 0:   log likelihood =  -3811.128  
Iteration 1:   log likelihood = -3376.4631  
Iteration 2:   log likelihood =  -3375.794  
Iteration 3:   log likelihood =  -3375.794  

Probit regression                                       Number of obs =  5,500
                                                        LR chi2(1)    = 870.67
                                                        Prob > chi2   = 0.0000
Log likelihood = -3375.794                              Pseudo R2     = 0.1142

------------------------------------------------------------------------------
           Y | Coefficient  Std. err.      z    P>|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
           X |   .0832308    .002921    28.49   0.000     .0775058    .0889558
       _cons |  -1.278027   .0474529   -26.93   0.000    -1.371033   -1.185021
------------------------------------------------------------------------------

**Comment by mcfanda** [comment]
is X a continuous or a categorical variable?

**Comment by srk7774** [comment]
It is difficult to say. X is the coupon amount the customers are redeeming. So It can be a discrete variable or a continuous variable.

**Comment by mcfanda** [comment]
You need to shape the data in a different way. First,  create an id variable with the same values for the same X. Use jReshape to obtain a file with two columns, one for Y=1 and one for Y=0. Then run generalized linear models with the "input method=Success/Faillures". 

![ex0](https://github.com/user-attachments/assets/47c71a1b-b100-446a-b4fb-afb7bf3c442f)

![ex1](https://github.com/user-attachments/assets/7b9e6507-2797-4b38-9961-1dbcac82e1ca)

![ex2](https://github.com/user-attachments/assets/7846e76c-d186-49a0-93f2-e30324564fa9)

**Comment by mcfanda** [comment]
at the moment, the R-squared obtained with this method should be ignored. The chi-squared is fine, and the loglikelihood is relatively correct. Relatively means that it can be used to compare models on the same data. It is, however, scaled differently than in stata.

**Comment by mcfanda** [comment]
with the data at hand, you can use jamovi "weights" function and use jamovi logistic regression (under regression menu). Than you get the correct R-squared. GAMLj at the moment does not consider weights (it will in the next versions)

**Comment by srk7774** [comment]
Thank you.
