### ISSUE TITLE
BUG: One-Way ANOVA analysis in the ANOVA module is not working.

### ISSUE THREAD

**Issue by ertugruluyar-github** [gamlj/gamlj#270]
Hi, I was doing assumption checks for my analysis' in my thesis.
I couldn't figure it out this, could you help me:
Is there a way to handle this assumptions in this module (or in the jamovi):
1. Homogenity of variances (Homogenity of level-1 variances) (Equality of level-1 variances for each level-2 unit) -> For this, can I use the residuals-predicted scatterplot?
I have used Levene's test in the 'One-Way ANOVA' test. There was a bug in this test. One-Way ANOVA module did not work ( jamovi version 2.5.9 via flatpak). So, I tried this on PSPP, Jasp and SPSS and the result is p<.05. But in this, there are less missing values that deleted because I didn't delete missing values from the dataset, meaning GAMLj3 module deleted automatically missing values that came from variables that I included in the module. So variances are not equal. Is this a problem for the analysis or Levene's test is not related to the this assumption?

2. Normality of level-2 residuals/errors
There is a save option for the residuals in the Options but there is no save option for the level-2 residuals (Am I wrong?). In this situation, how can I check this assumption?

3. Independence of each random effects -> For this, can I use the random effects correlations table in the result?

Thanks.

**Comment by mcfanda** [comment]
Sorry, it is a bit unclear what you asking. If you want to report a bug, please attach a .omv file with an example and a clear description of the issue. For questions, please use the https://forum.jamovi.org/

**Comment by ertugruluyar-github** [comment]
One-Way ANOVA module did not work (jamovi version 2.5.9 via flatpak).

Situation 1:
![image](https://github.com/user-attachments/assets/17286d6c-e7ef-4426-b42f-56e545f3566a)

Situation 2:
![image](https://github.com/user-attachments/assets/35410f8a-6815-4a63-b410-8f96d7c63b43)

But when I tried the the second analysis, my computer got crazy and my power down so quickly. I think there is 7061 sample in the data, so for this reason it got to much time to calculate. And there is a Note in the table.
![image](https://github.com/user-attachments/assets/efd481d5-751f-47a7-b493-434aff0556c6)

I think the there is no issue here, I am closing, thank you.
