### ISSUE TITLE
(Mixed) Simple effect labels are sorted alphabetically while estimates and stats are in correct order

### ISSUE THREAD

**Issue by bknakker** [gamlj/gamlj#79]
In a mixed model, I had a 4-level factor with poly contrasts and a 2-level factor. I inspected the simple effects of the 4-lvl with the 2-lvl as a moderator. The labels of the contrasts are ordered cubic, linear, quadratic, while all the other columns are ordered linear, quadratic, cubic, as expected. 

(PS: I checked the stats against emmeans by the way, and it appears that it gives the same t-stat, df and p-value with mismatching se and estimate. emmeans uses se-s that differ across contrasts, while for car the se-s are identical. It appears that car and emmeans reach the same conclusion via different paths. It's vaguely related but I thought that you might as well find it interesting.)

**Comment by Gootjes** [comment]
Related to that, in plots, when having a factor on the x-axis (in GLM), the levels are sorted alphabetically, instead of (what I expected) sorted based on the sorting of the levels of the variable.

**Comment by Gootjes** [comment]
![image](https://user-images.githubusercontent.com/37846483/54197495-63ca6c80-44c4-11e9-944b-b8cbbbdbd63b.png)

Relabeling a to y:

![image](https://user-images.githubusercontent.com/37846483/54197535-7d6bb400-44c4-11e9-93f0-d86be0201b23.png)

**Comment by bknakker** [comment]
> Related to that, in plots, when having a factor on the x-axis (in GLM), the levels are sorted alphabetically, instead of (what I expected) sorted based on the sorting of the levels of the variable.

Note that this preserves the mapping between data and labels, while in the issue I reported this mapping breaks. However, sticking to the level ordering defined for the data would be a nice feature.

**Comment by Gootjes** [comment]
Okay! That is different from my issue, I will file a new issue here on github.

**Comment by mcfanda** [comment]
We're bare struggling a bit with ggplot2 to respect data order for the factors. Forthcoming Version 1.5.0 should fix the issue

**Comment by mcfanda** [comment]
We're bare struggling a bit with ggplot2 to respect data order for the factors. Forthcoming Version 1.5.0 should fix the issue

**Comment by mcfanda** [comment]
Are you on macOs?

**Comment by bknakker** [comment]
For me, I was on macOS. Is that a factor? I think I've seen these on PC as well.

**Comment by mcfanda** [comment]
Did you check out the new version?

**Comment by bknakker** [comment]
Thanks, I downloaded the new version now. Re-did the analysis from scratch, and the bug was solved. However, starting from an older analysis (I think it was the one in which I observed the bug) it was still bad. So all analyses need to be redone from scratch even if the file still work to make sure that results are not mixed up. Maybe it would be nice to issue a warning for old files?

**Comment by Gootjes** [comment]
Changing anything in the dataset would update the analyses, and therefore
also the results. Would adding a filter variable that does nothing help
here? That would prevent the requirement to redo all analyses.
