### ISSUE TITLE
Error when adding polynomial terms

### ISSUE THREAD

**Issue by esintu** [gamlj/gamlj#81]
jamovi version: 0.9.6.7 (same issue on version - 0.9.5.17)
GAMLj version: 1.0.5
OS: Mac OS 10.14.4

When defining a model with a second degree polynomial by increasing the degree in the Components field under the Fixed Effects section, the term is added successfully to the Model Terms field (both as a main effect and as part of an interaction term), but the model fails with the following message at the top of the output section:

`'x' must be a character vector or a list of NULL or raw vectors`

It looks like it might be having some trouble converting the selected and superscripted number to the actual polynomial degree to be used. I'm including a screenshot with the extended debug message.

![jamovi error](https://user-images.githubusercontent.com/8835300/55878030-3f85ac80-5ba4-11e9-84fc-8fc9e5246879.jpg)

**Comment by mcfanda** [comment]
Thanks for the report. Forthcoming Version 1.5.0 fix that

**Comment by mcfanda** [comment]
Did you check out the new version?
