### ISSUE TITLE
Mixed models: singular fit of the model is silently ignored

### ISSUE THREAD

**Issue by bknakker** [gamlj/gamlj#87]
I don't know whether purposefully or not, but warning for singular fits is not displayed when fitting mixed models.

**Comment by mcfanda** [comment]
In theory the warning is captured, but I'm trying to understand why for some models the ""boundary (singular) fit: see ?isSingular" message is not produced when ran in jamovi.

**Comment by mcfanda** [comment]
ok, fixed. thanks for the catch
