### ISSUE TITLE
Mixed models: Instead of AIC, REML criterion at convergence is displayed

### ISSUE THREAD

**Issue by bknakker** [gamlj/gamlj#88]
The number displayed at the AIC seems to be what the lme4::lmer() %>% summary() textual output displays as "REML criterion at convergence". The result of extractAIC() does not match (I think this should yield the correct AIC).

**Comment by bknakker** [comment]
My previous note concerns the model summary on top (that value matches neither AIC nor extractAIC output). At the bottom, in the LRT part, in each row, the AIC of the _previous_ model is displayed (e.g. I have intercept+slope random, then the AIC of the random intercepts model is displayed in the one and only LRT row) - this might as well be a feature, but I find this confusing.

**Comment by mcfanda** [comment]
ok, thanks, I'll fix it

**Comment by mcfanda** [comment]
I fixed (upcoming version 1.5.3) the info table. As regards the LRT part, what it is displayed is simply what lmerTest::ranova() shows in the output. I left it like that so people can get documentation from the lmerttest docs. But I can change it if it can be made clearer

**Comment by mcfanda** [comment]
Hi, I've made some check. The AIC one gets form extractAIC() is always different form the AIC computed by SPSS mixed, and AFAIK, lower. However, the  "REML criterion at convergence" is always very close, or at least closer to SPSS AIC than it is the value of  extractAIC(). I wonder what SPSS does here

**Comment by bknakker** [comment]
I regarded lme4 output as benchmark, tacitly, and did not consider SPSS when I raised this issue. Even so, I hope that raising this was useful to you. Do you maybe have in mind any "best practice" that might be generally useful to implement, possibly even regardless of what SPSS says? I'm kind of a novice in lmm, and the subject of AIC, REML and model selection does not seem very clear to me.

**Comment by mcfanda** [comment]
yes, your issue was very relevant. After reading it, I implemented AIC  for the next version following extractAIC() function. I was just curious about what SPSS does, but it's not crucial for GAMLj, lme4 is benchmark. Thanks again.
