### ISSUE TITLE
Numerical variables as Factors

### ISSUE THREAD

**Issue by BTunca** [gamlj/gamlj#91]
Hi!

Very glad that you hav built this module!

I have a question, why only categorical and ordinal variables are allowed as Factors/Predictor Variables? It is not possible to use numeric variables?

Thank you!

Burak

**Comment by mcfanda** [comment]
Hi, continuous variables can be put in covariates. Please consider that we followed the some-how old-fashion SPSS terminology here, but "covariates" means "continuous variables" or "continuous predictors", nothing else. If you need to put a continuous variable as a factor, convert it into a nominal variable in the data tab, and then you can put it in "factors".

**Comment by BTunca** [comment]
Thanks a lot Marcello! For some reason I interpreted "covariates" as control variables in the model.

Anyway I managed to fit the model I wanted, great module, thanks again!

best,
Burak
