### ISSUE TITLE
Warning: Coefficients perfectly correlated

### ISSUE THREAD

**Issue by Scott-S-Hannah** [gamlj/gamlj#92]
Hi,

Trying to run a mixed effect model on a small data set I have but am getting the following warning: "Some of the coefficients cannot be estimated because they are perfectly correlated with other coefficients in the model." with the AIC output showing as -199.592.

The data is from a within-within design (crossover).
[Mixed_effect_data_SH.xlsx](https://github.com/gamlj/gamlj/files/3330786/Mixed_effect_data_SH.xlsx)

Any advice on dealing with this data?

Best,
Scott

**Comment by mcfanda** [comment]
Hi
there are cells in your design that are empty, that's why you get the error. You also have only one observation is "time=30". You can remove time=30 and Baseline (you only have it in one condition so you cannot to much with it anyway). and the model fits well
