### ISSUE TITLE
Feature request - 95% CI for slopes in graphs

### ISSUE THREAD

**Issue by Trebicky** [gamlj/gamlj#94]
Hi,
I really like GAMLj and its features and I am always happy to use it. But there is one feature, in regards to graphs plotting, that would be a great asset.

When plotting graphs, there is an option to display CIs, however, there are no CIs plotted for slopes... Would it be possible to plot CI bands (in the same fashion as one would see in case of plotting regression line and it CI in scatter plots) for slopes too? It would make it very easy to interpret the resulting models.

So far I am using homebrewed R script to draw them, which is a bit too much clumsy solution. Please, see an example of what I mean below.

Dots indicate the mean, error bars represent the 95% CI of the mean values, semi-transparent bow-tie areas indicate the 95% CI of the fixed effect of the difference.
![Slope CI](https://user-images.githubusercontent.com/55431044/65021349-30fba800-d92f-11e9-9993-f929da8f9f16.jpg)

**Comment by mcfanda** [comment]
Hi, thanks for the suggestion. I'm not sure, however, if this feature would really help. In gamlj plots you get the CI of the predicted values, thus you get the confidence bands for continuous IV and the CI for the categorical ones. How would you interpret the  semi-transparent bow-tie areas  you plotted? They do not seem to share the the plot metric? In particular, what does it mean that the area is null in the middle of the plot?
